name: Mobile UI Tests

on: 
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  maestro_tests:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          cd frontend
          npm install
          npm install -g expo-cli

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Select Xcode Version (Latest)
        run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

      - name: Start iPhone 16 Pro Max Simulator
        run: |
          UDID=$(xcrun simctl create "iPhone 16 Pro Max" "com.apple.CoreSimulator.SimDeviceType.iPhone-16-Pro-Max")
          xcrun simctl boot "$UDID"
          echo "Waiting for the simulator to be ready..."
          sleep 30
          xcrun simctl list devices

      - name: Start Expo and Open App in Simulator
        run: |
          cd frontend
          npx expo start --ios &
          sleep 40  # Wait for the server to initialize

      - name: Ensure Screenshots Directory Exists
        run: mkdir -p screenshots

      - name: Run Maestro Tests
        run: maestro test .github/workflows/maestro.yaml

      - name: Debug Screenshot Location
        if: always()
        run: |
          echo "Checking Maestro workspace for screenshots..."
          ls -R ~/.maestro/tests/ || echo "No screenshots found in ~/.maestro/tests/"
          ls -R screenshots/ || echo "No screenshots found in screenshots/"

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maestro-screenshots
          path: "**/screenshots/"
